<?php
/**
 * Saturn Developer Settings.
 *
 * DO NOT EDIT THIS FILE IN A TEXT EDITOR
 *
 * YOUR WEBSITE MUST BE SET TO DEVELOPER ENVIRONMENT FOR THESE SETTINGS TO APPLY.
 * THESE SETTINGS WILL BE IGNORED IN A PRODUCTION ENVIRONMENT FOR SECURITY REASONS.
 */

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//           //  If you edit this file in a text editor Saturn will display a warning saying the installation  //
//  WARNING  //  is not secure. This is because Saturn validates it against a checksum created whenever you    //
//           //  edit this file in the admin panel.                                                            //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const DEV_SHOW_PLUGINS = 0;
const SECURITY_PASSWORD_ALGORITHM = PASSWORD_DEFAULT;
const SECURITY_TOKEN_ALGORITHM = PASSWORD_DEFAULT;
