<?php
/**
 * Saturn Control Panel Settings.
 *
 * DO NOT EDIT THIS FILE IN A TEXT EDITOR
 */

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//           //  If you edit this file in a text editor Saturn will display a warning saying the installation  //
//  WARNING  //  is not secure. This is because Saturn validates it against a checksum created whenever you    //
//           //  edit this file in the admin panel.                                                            //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const SECURITY_PASSWORD_ALGORITHM = PASSWORD_DEFAULT;
