<div class="w-full h-screen bg-neutral-200">
    <ul class="w-full grid">
        <li class="hover:bg-neutral-300 hover:pl-4 p-2 w-full transition duration-200"><a href="/panel" class="w-full"><strong><?= $TL->TL('Saturn'); ?></strong></a></li>
        <li class="hover:bg-neutral-300 hover:pl-4 p-2 w-full transition duration-200"><a href="/panel/pages" class="w-full"><?= $TL->TL('Pages'); ?></a></li>
        <li class="hover:bg-neutral-300 hover:pl-4 p-2 w-full transition duration-200"><a href="/panel/settings" class="w-full"><?= $TL->TL('Settings'); ?></a></li>
    </ul>
</div>